#!/bin/bash            

# Course: CSCI-330      Assignment #5    Semester: Fall2020    
#                                                               
# NAME:Carlos Sanchez   Z-ID: z1729554            
#                                                               
# TA's Name: Venkata Sai Haswanth                                     
#                                                               
# Due: Friday 10/30/2020 by 11:59PM                              

if [ "$1" = help ]
then
   echo help entered
   exit 0
fi

case "$2" in

   new)

   if [ $# -gt 2 ]
   then
      dbhead="$3"
   else
      dbhead="Automobile Database"
   fi

   ls | grep "$1" -q
   if [ ! $? = 0 ]
   then
      echo $dbhead >> "$1"
      echo New database created
   else
      echo "$1" Already in Database, now exiting
   fi

   ;;

   add)
   if [ $# != 6 ]
   then
      echo Bad Parameters
      echo For more information, type \'"$0" help\'
      echo Now Exiting
      exit 1
   else
      if [ $5 -gt 1870 -a $5 -lt 2020 ]
      then
         linein="$3, $4, $5, $6"
         echo $linein >> $1
	 echo Successfully added a record to the database
   else
         echo Wrong Year
         echo For more information, type \'"$0" help\'
         echo Now Exiting
         exit 1
      fi
   fi

   ;;
   show)
   case "$3" in
      all)
      cat "$1"
      ;;
      single)
      sed -e '1 p' -n -e "$(($4 + 1)) p" "$1"
      ;;
      range)
      if [ $4 -ge $5 ]
      then
         echo Wrong Range
	 echo Please ensure that the starting range is larger \
	 than the ending range
	 exit 1
      else
         sed -e '1 p' -n -e "$(($4 + 1)),$(($5 + 1)) p" "$1"
      fi
      ;;
   esac
   ;;
   delete)
   case $3 in
      all)
      sed -i -e '2,$ d' $1
      echo All records deleted
      ;;
      single)
      sed -i -e "$(($4 + 1)) d" $1
      echo 1 record deleted
      ;;
      range)
      sed -i -e "$(($4 + 1)),$(($5 + 1)) d" $1
      echo records deleted
      ;;
   esac
   ;;  
  case		  
   *)
   echo Invalid Command
   echo For more information, type \'"$0" help\'
   echo Now Exiting
   exit 1;;
esac
