# once you add sub02.cc, you need to modify Makefile to include sub02.cc as a dependency
assignment02.exe: assignment02.cc assignment02.h sub02.cc
	g++ -std=c++11 -Wall -Wextra -pedantic -o assignment02.exe assignment02.cc sub02.cc

clean:
	rm *.exe
